# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HealthSystem_main(object):
    def setupUi(self, HealthSystem_main):
        HealthSystem_main.setObjectName("HealthSystem_main")
        HealthSystem_main.resize(1725, 1275)
        self.centralwidget = QtWidgets.QWidget(HealthSystem_main)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 110, 1661, 971))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("#frame{\n"
"    background-image: url(:/images/image/background.png);\n"
"    border-radius: 100px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Left_Frame = QtWidgets.QFrame(self.frame)
        self.Left_Frame.setGeometry(QtCore.QRect(30, 110, 311, 811))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Left_Frame.sizePolicy().hasHeightForWidth())
        self.Left_Frame.setSizePolicy(sizePolicy)
        self.Left_Frame.setStyleSheet("")
        self.Left_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Left_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Left_Frame.setObjectName("Left_Frame")
        self.Button_frame = QtWidgets.QFrame(self.Left_Frame)
        self.Button_frame.setGeometry(QtCore.QRect(30, 540, 261, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_frame.sizePolicy().hasHeightForWidth())
        self.Button_frame.setSizePolicy(sizePolicy)
        self.Button_frame.setMinimumSize(QtCore.QSize(120, 50))
        self.Button_frame.setMaximumSize(QtCore.QSize(16777214, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(210, 207, 233, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 207, 233, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 207, 233, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 207, 233, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 207, 233, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 207, 233, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 207, 233, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 207, 233, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 207, 233, 100))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Button_frame.setPalette(palette)
        self.Button_frame.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Button_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Button_frame.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    border:none;\n"
"    border-radius:10px\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(153, 153, 153);\n"
"}\n"
"")
        self.Button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Button_frame.setLineWidth(1)
        self.Button_frame.setObjectName("Button_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Button_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_main = QtWidgets.QPushButton(self.Button_frame)
        self.button_main.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_main.setFont(font)
        self.button_main.setFlat(False)
        self.button_main.setObjectName("button_main")
        self.verticalLayout.addWidget(self.button_main)
        self.button_goSQL = QtWidgets.QPushButton(self.Button_frame)
        self.button_goSQL.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_goSQL.setFont(font)
        self.button_goSQL.setObjectName("button_goSQL")
        self.verticalLayout.addWidget(self.button_goSQL)
        self.button_close2 = QtWidgets.QPushButton(self.Button_frame)
        self.button_close2.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.button_close2.setFont(font)
        self.button_close2.setObjectName("button_close2")
        self.verticalLayout.addWidget(self.button_close2)
        self.Left_bg = QtWidgets.QLabel(self.Left_Frame)
        self.Left_bg.setGeometry(QtCore.QRect(10, 10, 291, 781))
        self.Left_bg.setStyleSheet("background-color: rgba(101, 102, 153, 59)")
        self.Left_bg.setText("")
        self.Left_bg.setObjectName("Left_bg")
        self.line = QtWidgets.QFrame(self.Left_Frame)
        self.line.setGeometry(QtCore.QRect(40, 80, 241, 16))
        palette = QtGui.QPalette()
        self.line.setPalette(palette)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.Left_Frame)
        self.label_2.setGeometry(QtCore.QRect(120, 30, 131, 51))
        self.label_2.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Left_Frame)
        self.label_3.setGeometry(QtCore.QRect(60, 20, 61, 61))
        self.label_3.setStyleSheet("image: url(:/images/image/info_small.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.Left_Frame)
        self.textBrowser.setGeometry(QtCore.QRect(20, 110, 271, 431))
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(22, 38, 90, 200);\n"
"    border-radius:3px;\n"
"    color:rgb(0,0,0)\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.Left_bg.raise_()
        self.Button_frame.raise_()
        self.line.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.textBrowser.raise_()
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, -10, 1661, 111))
        self.frame_3.setStyleSheet("#frame_3{\n"
"    border-top-left-radius: 100px;\n"
"    border-top-right-radius: 100px;\n"
"    background-color: rgb(22, 38, 90);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.button_small = QtWidgets.QPushButton(self.frame_3)
        self.button_small.setGeometry(QtCore.QRect(1459, 50, 41, 34))
        self.button_small.setStyleSheet("border:none;\n"
"padding-bottom:5px;")
        self.button_small.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/image/green.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_small.setIcon(icon)
        self.button_small.setObjectName("button_small")
        self.button_close = QtWidgets.QPushButton(self.frame_3)
        self.button_close.setGeometry(QtCore.QRect(1520, 50, 51, 34))
        self.button_close.setStyleSheet("border:none;\n"
"padding-bottom:5px;")
        self.button_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/image/red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon1)
        self.button_close.setObjectName("button_close")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(600, 50, 641, 41))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(-50, 90, 1711, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.line_3.setPalette(palette)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(370, 140, 1221, 761))
        self.stackedWidget.setObjectName("stackedWidget")
        self.init_page = QtWidgets.QWidget()
        self.init_page.setObjectName("init_page")
        self.frame_7 = QtWidgets.QFrame(self.init_page)
        self.frame_7.setGeometry(QtCore.QRect(180, 370, 841, 111))
        self.frame_7.setStyleSheet("#frame_7{\n"
"    background-color: rgba(101, 102, 153, 59);\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.init_msg = QtWidgets.QTextBrowser(self.frame_7)
        self.init_msg.setGeometry(QtCore.QRect(10, 30, 821, 71))
        self.init_msg.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    font-size:9pt;\n"
"    font-weight:400;\n"
"    border-radius:3px;\n"
"    align= \"center\";\n"
"}")
        self.init_msg.setObjectName("init_msg")
        self.button_main_2 = QtWidgets.QPushButton(self.init_page)
        self.button_main_2.setGeometry(QtCore.QRect(450, 590, 259, 80))
        self.button_main_2.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.button_main_2.setFont(font)
        self.button_main_2.setStyleSheet("QPushButton{\n"
"    color:rgb(0, 236, 0);\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color: rgba(153, 153, 153, 100);\n"
"    font: 75 20pt \"微软雅黑\";\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(153, 153, 153);\n"
"}")
        self.button_main_2.setFlat(False)
        self.button_main_2.setObjectName("button_main_2")
        self.stackedWidget.addWidget(self.init_page)
        self.supervision_page = QtWidgets.QWidget()
        self.supervision_page.setObjectName("supervision_page")
        self.frame_2 = QtWidgets.QFrame(self.supervision_page)
        self.frame_2.setGeometry(QtCore.QRect(30, 260, 561, 481))
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: rgba(101, 102, 153, 59);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 541, 461))
        self.label_4.setStyleSheet("background-color: rgba(22, 38, 90, 200);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 61, 61))
        self.label_5.setStyleSheet("image: url(:/images/image/enterCheck.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(80, 30, 131, 51))
        self.label_6.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(30, 80, 491, 20))
        self.label_7.setObjectName("label_7")
        self.enter_pic = QtWidgets.QLabel(self.frame_2)
        self.enter_pic.setGeometry(QtCore.QRect(30, 120, 161, 231))
        self.enter_pic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enter_pic.setText("")
        self.enter_pic.setObjectName("enter_pic")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(230, 120, 81, 181))
        self.label_9.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(40, 380, 131, 51))
        self.label_10.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(290, 380, 91, 51))
        self.label_11.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_11.setObjectName("label_11")
        self.enter_name = QtWidgets.QTextBrowser(self.frame_2)
        self.enter_name.setGeometry(QtCore.QRect(300, 130, 171, 41))
        self.enter_name.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.enter_name.setObjectName("enter_name")
        self.enter_ide = QtWidgets.QTextBrowser(self.frame_2)
        self.enter_ide.setGeometry(QtCore.QRect(300, 190, 171, 41))
        self.enter_ide.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.enter_ide.setObjectName("enter_ide")
        self.enter_phone = QtWidgets.QTextBrowser(self.frame_2)
        self.enter_phone.setGeometry(QtCore.QRect(320, 250, 171, 41))
        self.enter_phone.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.enter_phone.setObjectName("enter_phone")
        self.enter_HQcode = QtWidgets.QTextBrowser(self.frame_2)
        self.enter_HQcode.setGeometry(QtCore.QRect(170, 370, 111, 91))
        self.enter_HQcode.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"}")
        self.enter_HQcode.setObjectName("enter_HQcode")
        self.enter_temp = QtWidgets.QTextBrowser(self.frame_2)
        self.enter_temp.setGeometry(QtCore.QRect(380, 370, 161, 81))
        self.enter_temp.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"}")
        self.enter_temp.setObjectName("enter_temp")
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.enter_pic.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.enter_name.raise_()
        self.enter_ide.raise_()
        self.enter_phone.raise_()
        self.enter_HQcode.raise_()
        self.enter_temp.raise_()
        self.frame_4 = QtWidgets.QFrame(self.supervision_page)
        self.frame_4.setGeometry(QtCore.QRect(640, 260, 561, 481))
        self.frame_4.setStyleSheet("#frame_4{\n"
"    background-color: rgba(101, 102, 153, 59);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 541, 461))
        self.label_8.setStyleSheet("background-color: rgba(22, 38, 90, 200);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 61, 61))
        self.label_12.setStyleSheet("image: url(:/images/image/outCheck.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(80, 30, 131, 51))
        self.label_13.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(30, 80, 491, 20))
        self.label_14.setObjectName("label_14")
        self.out_pic = QtWidgets.QLabel(self.frame_4)
        self.out_pic.setGeometry(QtCore.QRect(30, 120, 161, 231))
        self.out_pic.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.out_pic.setText("")
        self.out_pic.setObjectName("out_pic")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(230, 120, 81, 181))
        self.label_15.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(40, 380, 131, 51))
        self.label_16.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(320, 380, 91, 51))
        self.label_17.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_17.setObjectName("label_17")
        self.out_name = QtWidgets.QTextBrowser(self.frame_4)
        self.out_name.setGeometry(QtCore.QRect(300, 130, 171, 41))
        self.out_name.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.out_name.setObjectName("out_name")
        self.out_temp = QtWidgets.QTextBrowser(self.frame_4)
        self.out_temp.setGeometry(QtCore.QRect(410, 370, 131, 81))
        self.out_temp.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"}")
        self.out_temp.setObjectName("out_temp")
        self.out_ide = QtWidgets.QTextBrowser(self.frame_4)
        self.out_ide.setGeometry(QtCore.QRect(300, 190, 171, 41))
        self.out_ide.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.out_ide.setObjectName("out_ide")
        self.out_HQcode = QtWidgets.QTextBrowser(self.frame_4)
        self.out_HQcode.setGeometry(QtCore.QRect(170, 370, 111, 91))
        self.out_HQcode.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"}")
        self.out_HQcode.setObjectName("out_HQcode")
        self.out_phone = QtWidgets.QTextBrowser(self.frame_4)
        self.out_phone.setGeometry(QtCore.QRect(320, 250, 171, 41))
        self.out_phone.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.out_phone.setObjectName("out_phone")
        self.frame_5 = QtWidgets.QFrame(self.supervision_page)
        self.frame_5.setGeometry(QtCore.QRect(60, 40, 501, 111))
        self.frame_5.setStyleSheet("#frame_5{\n"
"    background-color: rgba(101, 102, 153, 59);\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.enter_num = QtWidgets.QTextBrowser(self.frame_5)
        self.enter_num.setGeometry(QtCore.QRect(280, 20, 261, 91))
        self.enter_num.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"    color: rgb(28, 255, 16);\n"
"}")
        self.enter_num.setObjectName("enter_num")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 281, 71))
        self.label_18.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_18.setObjectName("label_18")
        self.frame_6 = QtWidgets.QFrame(self.supervision_page)
        self.frame_6.setGeometry(QtCore.QRect(670, 40, 501, 111))
        self.frame_6.setStyleSheet("#frame_6{\n"
"    background-color: rgba(101, 102, 153, 59);\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.enter_num_danger = QtWidgets.QTextBrowser(self.frame_6)
        self.enter_num_danger.setGeometry(QtCore.QRect(280, 20, 261, 91))
        self.enter_num_danger.setStyleSheet("QTextBrowser{\n"
"    background-color: rgba(101, 102, 153, 0);\n"
"    border-radius:3px;\n"
"    color: rgb(28, 255, 16);\n"
"}")
        self.enter_num_danger.setObjectName("enter_num_danger")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(10, 20, 281, 71))
        self.label_19.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_19.setObjectName("label_19")
        self.stackedWidget.addWidget(self.supervision_page)
        self.SQL_page = QtWidgets.QWidget()
        self.SQL_page.setObjectName("SQL_page")
        self.label_20 = QtWidgets.QLabel(self.SQL_page)
        self.label_20.setGeometry(QtCore.QRect(320, 30, 511, 101))
        self.label_20.setStyleSheet("color:rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:10px")
        self.label_20.setObjectName("label_20")
        self.Person_SQL = QtWidgets.QTableView(self.SQL_page)
        self.Person_SQL.setGeometry(QtCore.QRect(10, 130, 1201, 621))
        self.Person_SQL.setAlternatingRowColors(True)
        self.Person_SQL.setSortingEnabled(True)
        self.Person_SQL.setObjectName("Person_SQL")
        self.stackedWidget.addWidget(self.SQL_page)
        self.frame_3.raise_()
        self.line_3.raise_()
        self.Left_Frame.raise_()
        self.stackedWidget.raise_()
        HealthSystem_main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HealthSystem_main)
        self.statusbar.setObjectName("statusbar")
        HealthSystem_main.setStatusBar(self.statusbar)

        self.retranslateUi(HealthSystem_main)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HealthSystem_main)

    def retranslateUi(self, HealthSystem_main):
        _translate = QtCore.QCoreApplication.translate
        HealthSystem_main.setWindowTitle(_translate("HealthSystem_main", "MainWindow"))
        self.button_main.setText(_translate("HealthSystem_main", "实时监控"))
        self.button_goSQL.setText(_translate("HealthSystem_main", "人员数据库"))
        self.button_close2.setText(_translate("HealthSystem_main", "退出"))
        self.label_2.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:16pt;\">消息通知</span></p></body></html>"))
        self.label.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">@智能防疫系统·上位机监控管理软件</span></p></body></html>"))
        self.init_msg.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600; color:#ffaa00;\">正在等待与下位机建立连接</span></p></body></html>"))
        self.button_main_2.setText(_translate("HealthSystem_main", "建立连接"))
        self.label_6.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:16pt;\">签入信息</span></p></body></html>"))
        self.label_7.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" color:#ffffff;\">--------------------------------------------------------------------------------------</span></p></body></html>"))
        self.label_9.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:12pt;\">姓名：</span><br/></p><p><span style=\" font-size:12pt;\">身份：</span><br/></p><p><span style=\" font-size:12pt;\">手机号： </span></p></body></html>"))
        self.label_10.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:18pt;\">健康码：</span></p></body></html>"))
        self.label_11.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:18pt;\">体温：</span></p></body></html>"))
        self.enter_name.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.enter_ide.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.enter_phone.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.enter_HQcode.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.enter_temp.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_13.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:16pt;\">签出信息</span></p></body></html>"))
        self.label_14.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" color:#ffffff;\">--------------------------------------------------------------------------------------</span></p></body></html>"))
        self.label_15.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:12pt;\">姓名：</span><br/></p><p><span style=\" font-size:12pt;\">身份：</span><br/></p><p><span style=\" font-size:12pt;\">手机号： </span></p></body></html>"))
        self.label_16.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:18pt;\">健康码：</span></p></body></html>"))
        self.label_17.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:18pt;\">体温：</span></p></body></html>"))
        self.out_name.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.out_temp.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.out_ide.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.out_HQcode.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.out_phone.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.enter_num.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600;\">0</span></p></body></html>"))
        self.label_18.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:20pt;\">当前签入人数: </span></p></body></html>"))
        self.enter_num_danger.setHtml(_translate("HealthSystem_main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt; font-weight:600; color:#ff2d1a;\">0</span></p></body></html>"))
        self.label_19.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:20pt;\">当前异常人数: </span></p></body></html>"))
        self.label_20.setText(_translate("HealthSystem_main", "<html><head/><body><p><span style=\" font-size:36pt;\">人员管理数据库</span></p></body></html>"))
import res_rc
